[package]
org = "nixos"
name = "users_service"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = true
cloud = "docker"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.4.0"

