# This file contains most used configurations supported by Ballerina Code to Cloud
# All the fields are optional. If these fields are not specified, default value will be taken from the compiler.
# Full Code to Cloud specification can be accessed from https://github.com/ballerina-platform/ballerina-spec/blob/master/c2c/code-to-cloud-spec.md
# Uncomment Any field below if you want to override the default value.

# Settings related to artifacts generation
#[settings]
#buildImage = true # Build the Docker image while building the project
#thinJar = true # Use the thin jars in the container
#
# Properties related to the container image
[container.image]
name = "api_gateway" # Name of the container image
#repository = "ballerina" # Container repository to host the container
#tag = "latest" # Tag of the container
#base = "ballerina/jvm-runtime:2.0" # Base container of the container image

# Copy the files to the container image
[[container.copy.files]]
sourceFile = "./resources/private.key" # Path to the external file
target = "/home/ballerina/resources/private.key" # Path of the file within the container

[[container.copy.files]]
sourceFile = "./resources/public.crt" # Path to the external file
target = "/home/ballerina/resources/public.crt" # Path of the file within the container

# External files required for the code
#[[cloud.config.maps]]
#file = "resource/file.txt" # Path of the external file
#mount_dir = "/home/ballerina/resource" # Directory of the file within the container
#
# Environment variables required for the application
#[[cloud.config.envs]]
#key_ref = "FOO" # Key of the environment variable
#name = "foo" # Name of the env if it is different from the key
#config_name = "module-foo" # Name of the config config map
#
# Properties related to the deployment
#[cloud.deployment]
#min_memory = "100Mi" # Minimum memory allocated to the container
#max_memory = "512Mi" # Maximum memory allocated to the container
#min_cpu = "200m" # Minimum CPU allocated to the container
#max_cpu = "500m" # Maximum CPU allocated to the container
#
# Matrices to auto-scale the container
#[cloud.deployment.autoscaling]
#min_replicas = 1 # Minimum number of replicas of the container alive at a given time
#max_replicas = 2 # Maximum number of replicas of the container alive at a given time
#cpu = 50 # CPU Utilization threshold for spawning a new instance
#
# Probe to indicate whether the container is ready to respond to requests. No readiness probe will be generated if not specified
#[cloud.deployment.probes.readiness]
#port = 9091 # Port of the readiness probe endpoint
#path = "/probes/readyz" # Endpoint of the readiness probe
#
# Probe to indicate whether the container is running. No liveness probe will be generated if not specified
#[cloud.deployment.probes.liveness]
#port = 9091 # Port of the liveness probe endpoint
#path = "/probes/healthz" # Endpoint of the liveness probe
#
# Volume definitions of the application. No default volumes will be generated if not specified
#[[cloud.deployment.storage.volumes]]
#name = "volume1" # Name of the volume
#local_path = "files" # Path of the volume
#size = "2Gi" # Maximum size of the volume
#
# Properties related to the builder image of the multistage build
#[graalvm.builder]
#base = "ghcr.io/graalvm/native-image-community:17-ol8" # base image of the builder image
#buildCmd = "native-image -jar hello.jar hello" # RUN statement to build the native image
#

[[cloud.config.secrets]]
file = "Config.toml"